# Generated by Django 3.0.8 on 2020-08-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(help_text='Name of your friend', max_length=120)),
                ('Contact_Number', models.IntegerField(help_text='Contact Number', max_length=12)),
            ],
        ),
    ]
